java_library(
    name = "commands",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//robot-java/src/main/java/frc/robot/subsystems",
        "@allwpilib//libraries/java/wpilibNewCommands",
        "@allwpilib//libraries/java/wpilibj",
    ],
)
