cc_library(
    name = "commands",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    visibility = ["//visibility:public"],
    deps = [
        "//robot-cpp/subsystems",
        "@allwpilib//dependencies/cpp/wpilibNewCommands",
        "@allwpilib//dependencies/cpp/wpilibc",
    ],
)
