cc_library(
    name = "subsystems",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    visibility = ["//visibility:public"],
    deps = [
        "@allwpilib//libraries/cpp/wpilibNewCommands",
        "@allwpilib//libraries/cpp/wpilibc",
        "@navx//dependencies/cpp/navx",
    ],
)
