java_library(
    name = "subsystems",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@allwpilib//libraries/java/hal",
        "@allwpilib//libraries/java/wpilibNewCommands",
        "@allwpilib//libraries/java/wpilibj",
        "@allwpilib//libraries/java/wpimath",
        "@navx//dependencies/java/navx",
    ],
)
